version: 2
jobs:

  init:
    docker:
      - image: mateuszsiek/nodejs-chrome
    steps:
        - checkout
        - restore_cache:
            key: v1-dependencies-{{ checksum "package.json" }}

        # Log the current branch
        - run:
            name: Show current branch
            command: echo ${CIRCLE_BRANCH}

        # Install project dependencies
        - run:
            name: Install local dependencies
            command: yarn
        - save_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
            paths:
                - node_modules

  unit-test:
    docker:
      - image: mateuszsiek/nodejs-chrome
    steps:
        - checkout
        - restore_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
        - run:
            name: Testing
            command: yarn test:ci
        - run:
            name: Coverage
            command: yarn coverage

  build:
    docker:
      - image: mateuszsiek/nodejs-chrome
    steps:
        - checkout
        - restore_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
##        - run:
##            name: Linting
##            command: yarn lint
        - run:
            name: Building
            command: |
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                    yarn build:prod
                else
                    yarn build:dev
                fi
        - save_cache:
            key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            paths:
                - dist
                - scripts
                - ~/.ssh

  e2e-test:
    docker:
      - image: mateuszsiek/nodejs-chrome
    steps:
        - checkout
        - restore_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
        - restore_cache:
            key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        - run:
            name: E2E tests
            command: |
                yarn serve &
                yarn e2e:ci --config baseUrl=http://127.0.0.1:4400

  e2e-smoke-test-dev:
    docker:
      - image: mateuszsiek/nodejs-chrome
    steps:
        - checkout
        - restore_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
        - run:
            name: E2E smoke tests dev
            command: yarn e2e:ci --config baseUrl=http://dev.haveadrink.msiek.com

  e2e-smoke-test-prod:
    docker:
      - image: mateuszsiek/nodejs-chrome
    steps:
        - checkout
        - restore_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
        - run:
            name: E2E smoke tests production
            command: yarn e2e:ci --config baseUrl=http://haveadrink.msiek.com

  deploy-prod:
    docker:
      - image: mateuszsiek/nodejs-chrome
    steps:

        # Restore local dependencies from cache
        - restore_cache:
            key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

        - run:
            name: Deploy to digital ocean
            command: bash ./scripts/deploy.sh
            environment:
                DOMAIN_NAME: haveadrink.msiek.com

  deploy-dev:
    docker:
      - image: mateuszsiek/nodejs-chrome
    steps:
        # Restore local dependencies from cache
        - restore_cache:
            key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

        - run:
            name: Deploy to digital ocean
            command: bash ./scripts/deploy.sh
            environment:
                DOMAIN_NAME: dev.haveadrink.msiek.com


workflows:
    version: 2
    # The build and deploy workflow
    build_and_deploy:
        jobs:
            - init

            - unit-test:
                requires:
                    - init

            - build:
                requires:
                    - init

            - e2e-test:
                requires:
                    - build

            - deploy-prod:
                requires:
                    - unit-test
                    - e2e-test
                    - build
                filters:
                    branches:
                        only: master

            - deploy-dev:
                requires:
                    - build
                filters:
                    branches:
                        ignore: master

            - e2e-smoke-test-dev:
                requires:
                    - deploy-dev
                filters:
                    branches:
                        ignore: master

            - e2e-smoke-test-prod:
                requires:
                    - deploy-prod
                filters:
                    branches:
                        only: master
